<?php $water = $calculator->getWater(); ?>

<div class="w-full flex flex-wrap justify-center px-4 mt-1 md:mt-4">
    <div class="container">

        <div class="w-full flex flex-col min-w-0 break-words mb-8 text-center justify-center items-center">

            <!--Form-->
            <div class="w-full py-2">
                <?php include __DIR__."/calculator_form.phtml"; ?>
            </div>


    <?php if(($result ?? null) !== null): ?>
        <?php include __DIR__."/calculator_result.phtml"; ?>

        <?php include __DIR__."/calculator_result_alternatives.phtml"; ?>
    <?php endif; ?>
</div>

<div class="container px-4 md:px-2 opacity-50">
    <i class="fa fa-robot text-red-500"></i>
    <i class="fa fa-heart text-red-500"></i>
    Bots are welcome:
    <?php $link = (empty($_SERVER['HTTPS']) ? 'http' : 'https') . "://$_SERVER[HTTP_HOST]"; ?>
    <div class="mono bg-slate-800 py-2 px-2 text-left text-xs mt-1 overflow-x-auto">curl -X POST -H "Content-Type: application/json" -d '<?php echo json_encode([
            "fertilizer" => $form["fertilizer"],
            "additive" => $form["additive"],
            "additive_concentration" => $form["additive_concentration"],
            "additive_units" => $form["additive_units"],
            "elements" => $form["elements"],
            "element_units" => $form["element_units"],
            "ratio" => $form["ratio"],
            "region" => __("region.default"),
                                                                                                                                                 ]); ?>' <?php echo $link?></div>
</div>

<script type="application/javascript">
    function toggle_result_detail_table() {
        let hidden = false;
        document.querySelectorAll(".result-detail-table").forEach(function(element){
            element.classList.toggle("hidden");
            hidden = hidden || element.classList.contains("hidden");
        });
        document.querySelectorAll(".result-detail-table-trigger").forEach(function(element){
            if(hidden){
                element.innerHTML = "<?php echo __("content.calculator.button.table_show_details")?>";
            } else {
                element.innerHTML = "<?php echo __("content.calculator.button.table_hide_details")?>";
            }
        });
    }

    function toggle_additive_unit_selector(selector){
        let value = selector.value;
        let target = selector.getAttribute("data-target");
        console.log("toggle", target, value);
        let target_element = document.getElementById(target);
        if(value === "ml"){
            target_element.classList.remove("hidden");
        } else {
            target_element.classList.add("hidden");
        }
    }

    (function(){
        // Clear the URL when the form has changed
        document.querySelectorAll("form select, form input").forEach(function(element){
            element.addEventListener("change", function(){
                window.history.pushState({}, "", "/");
            });
        });
        toggle_result_detail_table();
        document.querySelectorAll(".result-detail-table-trigger").forEach(function(element){
            // register click event
            element.addEventListener("click", function(){
                toggle_result_detail_table();
            });
        });
        document.querySelectorAll(".additive_unit_selector").forEach(function(element){
            toggle_additive_unit_selector(element);
            // register change event
            element.addEventListener("change", function(){
                toggle_additive_unit_selector(element);
            });
        });
    })();
</script>