
<form method="POST" target="_self" action="#results" class="w-full flex flex-wrap">

    <div class="w-full md:w-1/2 mt-1 flex flex-wrap justify-start items-start self-start">
        <div class="w-full px-2 py-2">
            <div class="w-full px-4 py-4 text-left bg-slate-700 shadow-lg rounded relative">
                <label for="fertilizer" class="font-semibold text-green-200">
                    <?php echo __("content.form.fertilizer.label")?>
                </label>
                <br/>
                <?php $fertilizers = $calculator->getFertilizers(); ?>
                <select name="fertilizer" id="fertilizer" class="w-full bg-slate-800 text-slate-200 rounded px-3 py-2 outline-none">
                    <?php foreach ($fertilizers as $name => $fertilizer): ?>
                        <option value="<?php echo $name ?>" <?php echo $name == $form["fertilizer"] ? "selected" : "" ?>
                                data-ratio="<?php echo round($fertilizer["ratio"], 2) ?>">
                            <?php echo $name ?> (<?php echo round($fertilizer["ratio"], 2) ?>:1)
                        </option>
                    <?php endforeach; ?>
                    <option value="" data-ratio="3.5" <?php echo $form["fertilizer"] === "" ? "selected" : "" ?>>
                        <?php echo __("content.form.fertilizer.option.none") ?>
                    </option>
                </select>
                <p class="text-xs pt-2 text-slate-400">
                    <?php echo __("content.form.fertilizer.description")?>
                </p>
            </div>
        </div>
        <?php foreach ($calculator->getAdditives() as $element => $additives): ?>
            <div class="w-full md:w-1/2 px-2 py-2">
                <div class="w-full px-4 py-4 text-left bg-slate-700 shadow-lg rounded relative">
                    <label for="additive_<?php echo $element ?>" class="font-semibold <?php echo $element === "calcium" ? "text-red-200" : "text-sky-200" ?>">
                        <?php echo __("content.form.additive.$element.label")?>
                    </label>
                    <br/>
                    <div class="w-full flex flex-row">
                        <select name="additive[<?php echo $element ?>]" id="additive_<?php echo $element ?>"
                                onchange="(function(){
                                        let elm = document.getElementById('additive_<?php echo $element ?>');
                                        document.getElementById('additive_concentration_<?php echo $element ?>').value = elm.options[elm.selectedIndex].getAttribute('data-concentration');
                                        })()"
                                class="w-7/12 md:w-9/12 bg-slate-800 text-slate-200 rounded px-3 py-2 outline-none">
                            <?php foreach ($additives as $name => $additive): ?>
                                <option value="<?php echo $name ?>" <?php echo $name == ($form["additive"][$element] ?? "") ? "selected" : "" ?> data-concentration="<?php echo $additive["concentration"] ?>">
                                    <?php echo __("additive.$name") ?>
                                </option>
                            <?php endforeach; ?>
                            <option value="" <?php echo ($form["additive"][$element] ?? "") === "" ? "selected" : "" ?> data-concentration="100">
                                <?php echo __("content.form.additive.none") ?>
                            </option>
                        </select>
                        <select name="additive_units[<?php echo $element ?>]"
                                id="additive_unit_<?php echo $element ?>"
                                data-target="additive_concentration_wrapper_<?php echo $element ?>"
                                class="w-5/12 md:w-3/12 bg-slate-800 text-slate-200 rounded-r py-3 outline-none additive_unit_selector">
                            <?php foreach (["ml", "mg"] as $unit): ?>
                                <option value="<?php echo $unit ?>" <?php echo $unit == ($form["additive_units"][$element] ?? "ml") ? "selected" : "" ?>>
                                    <?php echo $unit ?>/L
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <p class="text-xs pt-2 text-slate-400 pb-2">
                        <?php echo __("content.form.additive.$element.description")?>
                    </p>

                    <div id="additive_concentration_wrapper_<?php echo $element ?>" class="w-full">
                        <label for="additive_concentration_<?php echo $element ?>" class="font-semibold text-slate-300">
                            <?php echo __("content.form.additive_concentration.label")?>
                        </label>
                        <br/>
                        <input type="number"
                               step="0.01"
                               min="0"
                               max="100"
                               name="additive_concentration[<?php echo $element?>]"
                               id="additive_concentration_<?php echo $element ?>"
                               class="w-full bg-slate-800 text-slate-200 rounded px-3 py-2 outline-none"
                               value="<?php echo $form["additive_concentration"][$element] ?? $additives[array_key_first($additives)]["concentration"] ?>" />
                        <p class="text-xs pt-2 text-slate-400">
                            <?php echo __("content.form.additive_concentration.description")?>
                        </p>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>

        <!--<div class="w-full md:w-1/3 px-2 py-2">
                            <div class="w-full px-4 py-4 text-left bg-slate-700 shadow-lg rounded relative">
                                <label for="region" class="font-semibold text-slate-900">
                                    <?php /*echo __("content.form.region.label")*/?>
                                </label>
                                <br/>
                                <select name="region" id="region" class="w-full bg-slate-800 text-slate-200 rounded px-3 py-2 outline-none">
                                    <?php /*foreach ($regions as $region => $name): */?>
                                        <option value="<?php /*echo $region */?>" <?php /*echo $region == $form["region"] ? "selected" : "" */?>>
                                            <?php /*echo __($name) */?>
                                        </option>
                                    <?php /*endforeach; */?>
                                </select>
                                <p class="text-xs pt-2 text-slate-400">
                                    <?php /*echo __("content.form.region.description")*/?>
                                </p>
                            </div>
                        </div>-->
    </div>
    <div class="w-full md:w-1/2 flex flex-wrap justify-center items-center">

        <div class="w-full flex flex-wrap self-start">
            <div class="w-full text-left px-2 py-2 ">
                <h6 class="w-full text-red-500 font-semibold">
                    <?php echo __("content.form.elements.title")?>
                </h6>
                <p class="text-xs pt-2 text-slate-400">
                    <?php echo __("content.form.elements.description")?>
                    <a href="https://duckduckgo.com/?q=<?php echo urlencode( __("content.calculator.google.query")) ?>"
                       target="_blank"
                       class="text-red-500 ">
                        <?php echo __("content.calculator.button.search_plz")?>
                    </a>
                </p>
            </div>

            <?php foreach ($available_elements as $element => $label): ?>
                <div class="w-1/2 md:w-1/2 px-2 py-2">
                    <div class="w-full px-4 py-4 text-left bg-slate-700 shadow-lg rounded relative">
                        <label for="elements_<?php echo $element ?>" class="font-semibold text-slate-300">
                            <?php echo __($label)?>
                        </label>
                        <br/>
                        <div class="w-full flex flex-row">
                            <input type="number"
                                   step="0.001"
                                   min="0"
                                   name="elements[<?php echo $element ?>]"
                                   id="elements_<?php echo $element ?>"
                                   class="w-7/12 md:w-9/12 bg-slate-800 text-slate-200 rounded-l px-3 py-2 outline-none"
                                   value="<?php echo $form["elements"][$element] ?? 0.0 ?>" />
                            <select name="element_units[<?php echo $element ?>]"
                                    id="element_unit_<?php echo $element ?>"
                                    class="w-5/12 md:w-3/12 bg-slate-800 text-slate-200 rounded-r py-3 outline-none">
                                <?php foreach (["mg", "mmol"] as $unit): ?>
                                    <option value="<?php echo $unit ?>" <?php echo $unit == ($form["element_units"][$element] ?? "mg") ? "selected" : "" ?>>
                                        <?php echo $unit ?>/L
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>

            <div class="w-full md:w-1/2 px-2 pt-2 ">
                <div class="w-full px-4 py-4 text-left bg-slate-700 shadow-lg rounded relative">
                    <label for="ratio" class="font-semibold text-slate-300">
                        <?php echo __("content.form.ratio.label")?>
                    </label>
                    <br/>
                    <input type="number"
                           step="0.01"
                           min="0"
                           name="ratio" id="ratio"
                           class="w-full bg-slate-800 text-slate-200 rounded px-3 py-2 outline-none"
                           value="<?php echo round($form["ratio"] ?? $fertilizers[array_key_first($fertilizers)]["ration"] ?? 0.0, 2) ?>" />
                    <p class="text-xs pt-2 text-slate-400">
                        <?php echo __("content.form.ratio.description")?>
                    </p>
                </div>
            </div>

            <div class="w-full md:w-1/2 px-2 pt-2 ">
                <div class="w-full px-4 py-4 text-left bg-slate-700 shadow-lg rounded relative">
                    <label for="volume" class="font-semibold text-slate-300">
                        <?php echo __("content.form.volume.label")?>
                    </label>
                    <br/>
                    <input type="number"
                           step="0.1"
                           min="0"
                           name="volume" id="volume" class="w-full bg-slate-800 text-slate-200 rounded px-3 py-2 outline-none" value="<?php echo $form["volume"] ?>" />
                    <p class="text-xs pt-2 text-slate-400">
                        <?php echo __("content.form.volume.description")?>
                    </p>
                </div>
            </div>


            <div class="w-full px-2 pb-2 ">
                <div class="w-full px-4 py-4 text-left  relative">
                    <label for="support_dilution" class="font-normal text-slate-300">
                        <input type="hidden" name="support_dilution" value="0" />
                        <input type="checkbox"
                               value="1"
                               name="support_dilution" id="support_dilution"
                               class="bg-slate-800 text-slate-200 rounded px-3 py-2 outline-none mr-2"
                            <?php echo ($form["support_dilution"] ?? false) ? "checked" : "" ?> />
                        <?php echo __("content.form.support_dilution.label")?>
                    </label>
                    <br/>
                    <p class="text-xs pt-2 text-slate-400">
                        <?php echo __("content.form.support_dilution.description")?>
                    </p>
                </div>
            </div>

        </div>

    </div>


    <div class="w-full  items-center justify-items-center pt-4 md:pt-4">
        <div class="w-full flex items-center justify-items-center justify-center">
            <button type="submit"
                    class="bg-red-500 text-white hover:bg-red-600 font-bold uppercase text-sm px-6 py-3 rounded shadow hover:shadow-lg outline-none border-0 focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150">
                <?php echo __("content.calculator.button.calculate")?>
            </button>
            <a href="?expert=1"
               class="bg-sky-500 text-white hover:bg-sky-600 font-bold uppercase text-sm px-6 py-3 rounded shadow hover:shadow-lg outline-none border-0 focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150 line">
                <?php echo __("content.calculator.button.expert")?>
            </a>
            <a href="?compare=1"
               class="bg-yellow-500 text-slate-900 hover:bg-yellow-600 font-bold uppercase text-sm px-6 py-3 rounded shadow hover:shadow-lg outline-none border-0 focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150 line">
                <?php echo __("content.calculator.button.compare")?>
            </a>
        </div>
    </div>
</form>


<script type="application/javascript">
    function onFertilizerChanged(event){
        let select = event.target;
        const ratio = parseFloat(select.options[select.selectedIndex].getAttribute("data-ratio"));
        if(ratio >= 2.9 && ratio <= 4.0){
            document.getElementById("ratio").value = ratio;
        }else if (ratio < 2.9){
            document.getElementById("ratio").value = 2.9;
        }else if (ratio > 4.0){
            document.getElementById("ratio").value = 4.0;
        }else{
            document.getElementById("ratio").value = 3.5;
        }
    }

    (function (){
        let fertilizer = document.getElementById("fertilizer");
        fertilizer.addEventListener("change", onFertilizerChanged);
        //onFertilizerChanged({target: fertilizer});
    })();
</script>