<div class="w-full flex flex-wrap justify-center px-4 mt-1 md:mt-4">
    <div class="container">

        <div class="w-full flex flex-col min-w-0 break-words mb-8 text-center justify-center items-center">

            <!--Form-->
            <div class="w-full py-2">
                <form method="POST" target="_self" action="?compare=1#results" class="w-full flex flex-wrap">

                    <div class="w-full md:w-1/2 mt-1 flex flex-wrap justify-start items-start self-start">

                        <!--<div class="w-full md:w-1/3 px-2 py-2">
                            <div class="w-full px-4 py-4 text-left bg-slate-700 shadow-lg rounded relative">
                                <label for="region" class="font-semibold text-slate-300">
                                    <?php /*echo __("content.form.region.label")*/?>
                                </label>
                                <br/>
                                <select name="region" id="region" class="w-full bg-slate-800 text-slate-200 rounded px-3 py-2 outline-none">
                                    <?php /*foreach ($regions as $region => $name): */?>
                                        <option value="<?php /*echo $region */?>" <?php /*echo $region == $form["region"] ? "selected" : "" */?>>
                                            <?php /*echo __($name) */?>
                                        </option>
                                    <?php /*endforeach; */?>
                                </select>
                                <p class="text-xs pt-2 text-slate-400">
                                    <?php /*echo __("content.form.region.description")*/?>
                                </p>
                            </div>
                        </div>-->


                        <div class="w-full px-2 py-2">
                            <div class="w-full px-4 py-4 text-left bg-slate-50 dark:bg-slate-700 shadow-lg rounded relative">
                                <label for="ratio" class="font-semibold text-slate-600 dark:text-slate-300">
                                    <?php echo __("content.form.ratio.label")?>
                                </label>
                                <br/>
                                <div class="flex items-center content-center">
                                    <input type="number"
                                           step="0.01"
                                           min="0"
                                           name="ratio" id="ratio" 
                                           class="w-full bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 rounded-l px-3 py-2 outline-none" 
                                           value="<?php echo $form["ratio"] ?>" />
                                    <span class="bg-slate-200 dark:bg-slate-900 text-slate-700 dark:text-slate-200 rounded-r px-3 py-2">:1</span>
                                </div>
                                <p class="text-xs pt-2 text-slate-500 dark:text-slate-400">
                                    <?php echo __("content.form.ratio.description")?>
                                </p>
                            </div>
                        </div>

                        <!--<div class="w-full md:w-1/2 px-2 py-2 ">
                            <div class="w-full px-4 py-4 text-left bg-slate-700 shadow-lg rounded relative">
                                <label for="density" class="font-semibold text-slate-300">
                                    <?php /*echo __("content.form.density.label")*/?>
                                </label>
                                <br/>
                                <input type="number"
                                       step="0.01"
                                       min="0"
                                       name="density" id="density" class="w-full bg-slate-800 text-slate-200 rounded px-3 py-2 outline-none" value="<?php /*echo $form["density"] */?>" />
                                <p class="text-xs pt-2 text-slate-400">
                                    <?php /*echo __("content.form.density.description")*/?>
                                </p>
                            </div>
                        </div>-->

                    </div>
                    <div class="w-full md:w-1/2 flex flex-wrap justify-start items-start py-3">
                        <div class="w-full px-2">
                            <div class="w-full px-4 py-4 text-left bg-slate-50 dark:bg-slate-700 shadow-lg rounded relative">
                                <div class="w-full text-left py-2">
                                    <h6 class="w-full text-red-500 font-semibold">
                                        <?php echo __("content.form.elements.title")?>
                                    </h6>
                                    <p class="text-xs pt-2 text-slate-500 dark:text-slate-400">
                                        <?php echo __("content.form.elements.description")?>
                                        <a href="https://duckduckgo.com/?q=<?php echo urlencode( __("content.calculator.google.query")) ?>"
                                        target="_blank"
                                        class="text-red-500">
                                            <?php echo __("content.calculator.button.search_plz")?>
                                        </a>
                                    </p>
                                </div>

                                <div class="flex flex-wrap">
                                    <?php foreach ($available_elements as $element => $label): ?>
                                        <div class="w-1/2 md:w-1/3 pb-4 pr-2">
                                            <label for="elements_<?php echo $element ?>" class="font-semibold text-slate-600 dark:text-slate-300">
                                                <?php echo __($label)?>
                                            </label>
                                            <br/>
                                            <div class="w-full flex flex-row">
                                                <input type="number"
                                                      step="0.001"
                                                      min="0"
                                                      name="elements[<?php echo $element ?>]"
                                                      id="elements_<?php echo $element ?>"
                                                      class="w-7/12 md:w-9/12 bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 rounded-l px-3 py-2 outline-none"
                                                      value="<?php echo $form["elements"][$element] ?? 0.0 ?>" />
                                                <select name="element_units[<?php echo $element ?>]"
                                                        id="element_unit_<?php echo $element ?>"
                                                        class="w-5/12 md:w-3/12 bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 rounded-r py-3 outline-none">
                                                    <?php foreach (["mg", "mmol"] as $unit): ?>
                                                        <option value="<?php echo $unit ?>" <?php echo $unit == ($form["element_units"][$element] ?? "mg") ? "selected" : "" ?>>
                                                            <?php echo $unit ?>/L
                                                        </option>
                                                    <?php endforeach; ?>
                                                </select>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        </div>
                    </div>



                    <div class="w-full items-center justify-items-center pt-4 md:pt-8">
                        <div class="flex flex-wrap gap-2 justify-center">
                            <button type="submit"
                                    class="px-2 py-2 md:px-6 md:py-3 bg-green-500 text-white hover:bg-green-600 font-bold uppercase text-sm rounded shadow hover:shadow-lg outline-none border-0 focus:outline-none ease-linear transition-all duration-150">
                                <?php echo __("content.calculator.button.calculate")?>
                            </button>
                            <a href="?regular=1"
                                class="px-2 py-2 md:px-6 md:py-3 bg-sky-500 text-white hover:bg-sky-600 font-bold uppercase text-sm rounded shadow hover:shadow-lg outline-none border-0 focus:outline-none ease-linear transition-all duration-150 line">
                                <?php echo __("content.calculator.button.regular")?>
                            </a>
                            <a href="?expert=1"
                                class="px-2 py-2 md:px-6 md:py-3 bg-sky-500 text-white hover:bg-sky-600 font-bold uppercase text-sm rounded shadow hover:shadow-lg outline-none border-0 focus:outline-none ease-linear transition-all duration-150 line">
                                <?php echo __("content.calculator.button.expert")?>
                            </a>
                            <!--
                            <a href="?wizard=1&p=<?php echo $payload_link?>"
                                class="px-2 py-2 md:px-6 md:py-3 bg-yellow-500 text-slate-900 hover:bg-yellow-600 font-bold uppercase text-sm rounded shadow hover:shadow-lg outline-none border-0 focus:outline-none ease-linear transition-all duration-150 line">
                                <?php echo __("content.calculator.button.wizard")?>
                            </a>
                            <a href="?builder=1&p=<?php echo $payload_link?>"
                                class="px-2 py-2 md:px-6 md:py-3 bg-yellow-500 text-slate-900 hover:bg-yellow-600 font-bold uppercase text-sm rounded shadow hover:shadow-lg outline-none border-0 focus:outline-none ease-linear transition-all duration-150 line">
                                <?php echo __("content.calculator.button.builder")?>
                            </a>
                        -->
                        </div>
                    </div>
                </form>
            </div>


            <?php if(($result ?? null) !== null): ?>
                <div class="w-full pr-4 py-2 mt-8" id="results">
                    <h6 class="text-red-500 text-4xl font-normal">
                        <?php echo __("content.comparator.result.title")?>
                    </h6>
                </div>

                <div class="w-full px-2 lg:px-6 pt-2 pb-8 overflow-x-auto"  id="result-table">
                    <table class="w-full text-slate-700 dark:text-slate-200">
                        <thead>
                        <tr>
                            <th class="pr-2 text-left font-semibold"><?php echo __("content.form.fertilizer.label")?></th>
                            <th class="px-2 text-right font-semibold"><?php echo __("content.form.state.label")?></th>
                            <th class="px-2 text-center font-semibold"><?php echo __("content.form.ml.label")?></th>
                            <th class="px-2 text-center font-semibold"><?php echo __("content.form.dilution.label")?></th>
                            <th class="pl-2 text-center font-semibold"><?php echo __("content.form.ratio.label")?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($result as $fertilizer => $states): ?>
                            <tr>
                                <td class="text-left text-green-500" colspan="5"><?php echo $fertilizer ?></td>
                            </tr>
                            <?php foreach ($states as $state => $_results): ?>
                                <?php $color = match ($state){
                                    \Webklex\CalMag\Enums\GrowState::Propagation->value => "bg-indigo-500 dark:bg-indigo-700 border border-indigo-600 dark:border-indigo-800 text-white",
                                    \Webklex\CalMag\Enums\GrowState::Vegetation->value => "bg-green-500 dark:bg-green-700 border border-green-600 dark:border-green-800 text-white",
                                    \Webklex\CalMag\Enums\GrowState::Flower->value => "bg-cyan-500 dark:bg-cyan-700 border border-cyan-600 dark:border-cyan-800 text-white",
                                    \Webklex\CalMag\Enums\GrowState::LateFlower->value => "bg-violet-500 dark:bg-violet-700 border border-violet-600 dark:border-violet-800 text-white",
                                    default => "bg-slate-100 dark:bg-slate-700",
                                }; ?>
                                <tr>
                                    <td></td>
                                    <td class="px-2 text-right <?php echo $color?>"><?php echo __("content.calculator.state.$state") ?></td>
                                    <td class="px-2 <?php echo $color?>"><?php echo $_results["fertilizer"]["ml"] ?>ml/L</td>
                                    <td class="px-2 <?php echo $color?>"><?php echo number_format($_results["water"] * 100, 2) ?>%</td>
                                    <td class="pl-2 <?php echo $color?>"><?php echo round($_results["ratio"],2) ?>:1</td>
                                </tr>

                            <?php endforeach; ?>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>

                <?php if(isset($result["results"]) && is_array($result["results"])): ?>
                <?php foreach ($result["results"] as $state => $results): ?>
                    <div class="w-full pr-4 py-2">
                        <h6 class="text-red-500 text-4xl font-normal">
                            <?php echo __("content.calculator.state.$state")?>
                            <span class="text-xs" title="<?php echo __("content.form.ratio.label") ?>">(<?php echo round($results["ratio"], 2) ?>:1)</span>
                        </h6>
                    </div>
                    <div class="flex flex-wrap w-full py-2">

                        <div class="flex flex-wrap w-full md:w-1/3 pb-2 justify-start items-start self-start">

                            <?php foreach ([
                                               "calcium" => $results["target"]["elements"]["calcium"],
                                               "magnesium" => $results["target"]["elements"]["magnesium"],
                                           ] as $element => $value): ?>
                                <div class="w-full md:w-1/2 px-2 py-2">
                                    <div class="w-full px-4 py-4 text-left bg-slate-50 dark:bg-slate-700 shadow-lg rounded relative">
                                        <div class="font-semibold text-slate-600 dark:text-slate-300">
                                            <?php echo __("content.form.element.$element.label")?>
                                        </div>
                                        <div class="text-slate-700 dark:text-slate-200">
                                            <?php echo number_format($water["elements"][$element], 2, ",", "."); ?> mg
                                            /
                                            <?php echo number_format($value, 2, ",", "."); ?>
                                            mg
                                        </div>

                                        <?php if (isset($results["missing"][$element])): ?>
                                            <?php $missing = number_format($results["missing"][$element], 2, ",", "."); ?>
                                            <div class="text-red-500 text-xs" title="<?php echo __('content.calculator.missing', ["value" => $missing,"name" => __("content.form.element.$element.label")] )?>">
                                                <?php echo $results["missing"][$element] > 0 ? "+" : "" ?><?php echo $missing ?> mg
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                            <?php if(isset($results['suggested_additive'])): ?>
                            <?php foreach($results['suggested_additive'] as $element => $suggested_additive): ?>
                                <div class="w-1/2 px-2 py-2">
                                    <div class="w-full px-4 py-4 text-left bg-slate-50 dark:bg-slate-700 shadow-lg rounded relative">
                                        <span class="font-semibold text-slate-600 dark:text-slate-300">
                                            <?php echo __("additive.".$suggested_additive["additive"]); ?>
                                        </span>
                                        <br/>
                                        <span class="text-slate-700 dark:text-slate-200"><?php echo number_format($suggested_additive["concentration"] *10,2, ",", "."); ?> g/L</span>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                            <?php endif; ?>
                        </div>

                        <div class="w-full md:w-1/3 px-3 py-2">
                            <table class="table w-full text-slate-700 dark:text-slate-200">
                                <?php $colspan = count($results["elements"] ?? []); ?>
                                <?php $magnesium_additive = isset($results["additive"]["magnesium"]["ml"]) ? $calculator->getAdditiveComponents("magnesium", $results["additive"]["magnesium"]["ml"]) : null; ?>
                                <?php $calcium_additive = isset($results["additive"]["calcium"]["ml"]) ? $calculator->getAdditiveComponents("calcium", $results["additive"]["calcium"]["ml"]) : null; ?>

                                <tr class="bg-red-500 text-white">
                                    <td colspan="<?php echo $colspan; ?>" class="font-semibold text-left px-2 py-1">
                                        <?php echo __("content.calculator.water.label")?>
                                    </td>
                                </tr>
                                <tr>
                                    <?php foreach ($results["elements"] as $element => $value): ?>
                                        <td class="text-left font-semibold px-2 py-1"><?php echo __("content.form.element.$element.label")?></td>
                                    <?php endforeach; ?>
                                </tr>
                                <tr>
                                    <?php foreach ($results["elements"] as $element => $value): ?>
                                        <td class="text-left pb-2 px-2 py-1">
                                            <?php if (isset($water["elements"][$element])): ?>
                                                <?php echo number_format($water["elements"][$element], 2, ",", ".") ?> mg/L
                                            <?php else: ?>
                                                -
                                            <?php endif; ?>
                                        </td>
                                    <?php endforeach; ?>
                                </tr>


                                <?php if($results["water"] > 0): ?>
                                    <tr class="bg-sky-500 dark:bg-sky-700 text-white">
                                        <td colspan="<?php echo $colspan -1; ?>" class="font-semibold text-left px-2 py-1"><?php echo __("dilution.label") ?>:</td>
                                        <td class="font-semibold text-right px-2 py-1">
                                            <?php echo number_format($results["dilution"]/$results["water"], 2, ",", "") ?>:1
                                        </td>
                                    </tr>
                                    <tr>
                                        <?php $factor = $results["water"]/$results["dilution"]; ?>
                                        <?php foreach ($results["elements"] as $element => $value): ?>
                                            <td class="text-left pb-2 px-2 py-1">
                                                <?php if (isset($water["elements"][$element])): ?>
                                                    <?php echo number_format($water["elements"][$element]*$results["dilution"], 2, ",", ".") ?> mg/L
                                                <?php else: ?>
                                                    -
                                                <?php endif; ?>
                                            </td>
                                        <?php endforeach; ?>
                                    </tr>
                                <?php endif; ?>

                                    <?php foreach($results['suggested_additive'] as $element => $suggested_additive): ?>
                                        <tr class="bg-green-500 dark:bg-green-700 text-white">
                                            <td colspan="<?php echo $colspan -1; ?>" class="font-semibold text-left px-2 py-1">
                                                <?php echo __("additive.".$suggested_additive["additive"]); ?>
                                            </td>
                                            <td class="font-semibold text-right px-2 py-1">
                                                <?php echo number_format($suggested_additive["concentration"] *10,2, ",", "."); ?> g/L
                                            </td>
                                        </tr>
                                        <tr>
                                            <?php foreach ($results["elements"] as $_element => $value): ?>
                                                <td class="text-left px-2 py-1">
                                                    <?php if (isset($suggested_additive["real"][$_element])): ?>
                                                        <?php echo number_format($suggested_additive["real"][$_element] * $suggested_additive["ml"], 2, ",", "."); ?> mg/L
                                                    <?php else: ?>
                                                        -
                                                    <?php endif; ?>
                                                </td>
                                            <?php endforeach; ?>
                                        </tr>
                                    <?php endforeach; ?>
                                </table>

                        </div>

                        <div class="flex flex-wrap w-full md:w-1/3 pb-2">
                            <div class="w-full px-3 py-2 text-left text-slate-700 dark:text-slate-200">
                                <?php if($results["water"] > 0): ?>
                                    <?php echo __("content.calculator.result.deficiency.dilution", [
                                        "dilution" => '<span class="text-red-500 font-bold">'.round($results["dilution"]*1000,2)." ml</span>",
                                        "water" => '<span class="text-red-500 font-bold">'.round($results["water"]*1000,2)." ml</span>",
                                    ])?>
                                    <br />
                                <?php endif; ?>

                                <?php if($results["missing"]["calcium"] > 0 && $results["missing"]["magnesium"] > 0): ?>
                                    <?php echo __("content.calculator.result.deficiency.state.calcium_and_magnesium_missing", [
                                        "calcium" =>  number_format($results["missing"]["calcium"],2, ",", ""),
                                        "magnesium" =>  number_format($results["missing"]["magnesium"],2, ",", ""),
                                    ])?>
                                <?php elseif($results["missing"]["calcium"] > 0): ?>
                                    <?php echo __("content.calculator.result.deficiency.state.calcium_missing", [
                                        "calcium" =>  number_format($results["missing"]["calcium"],2, ",", ""),
                                    ])?>
                                <?php elseif($results["missing"]["magnesium"] > 0): ?>
                                    <?php echo __("content.calculator.result.deficiency.state.magnesium_missing", [
                                        "magnesium" =>  number_format($results["missing"]["magnesium"],2, ",", ""),
                                    ])?>
                                <?php elseif($results["missing"]["calcium"] < 0 && $results["missing"]["magnesium"] < 0): ?>
                                    <?php echo __("content.calculator.result.deficiency.state.calcium_and_magnesium_high", [
                                        "calcium" =>  number_format($results["missing"]["calcium"]*-1,2, ",", ""),
                                        "magnesium" =>  number_format($results["missing"]["magnesium"]*-1,2, ",", ""),
                                    ])?>
                                <?php elseif($results["missing"]["calcium"] < 0): ?>
                                    <?php echo __("content.calculator.result.deficiency.state.calcium_high", [
                                        "calcium" =>  number_format($results["missing"]["calcium"]*-1,2, ",", ""),
                                    ])?>
                                <?php elseif($results["missing"]["magnesium"] < 0): ?>
                                    <?php echo __("content.calculator.result.deficiency.state.magnesium_high", [
                                        "magnesium" =>  number_format($results["missing"]["magnesium"]*-1,2, ",", ""),
                                    ])?>
                                <?php else: ?>
                                    <?php echo __("content.calculator.result.deficiency.state.magnesium_and_calcium_ok")?>
                                <?php endif; ?>
                                <br />

                                <?php if($results["missing"]["calcium"] > 0 || $results["missing"]["magnesium"] > 0): ?>
                                    <?php if($results["fertilizer"]["ml"] > 0 && $results["additive"]["magnesium"]["ml"] > 0 && $results["additive"]["calcium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_and_magnesium_missing_with_all", [
                                            "magnesium_additive_ml" =>  number_format($results["additive"]["magnesium"]["ml"],2, ",", ""),
                                            "magnesium_additive_concentration" =>  $results["additive"]["magnesium"]["concentration"],
                                            "magnesium_additive_name" =>  __("additive.".$results["additive"]["magnesium"]["name"]),
                                            "calcium_additive_ml" =>  number_format($results["additive"]["calcium"]["ml"],2, ",", ""),
                                            "calcium_additive_concentration" =>  $results["additive"]["calcium"]["concentration"],
                                            "calcium_additive_name" =>  __("additive.".$results["additive"]["calcium"]["name"]),
                                            "fertilizer_ml" =>  number_format($results["fertilizer"]["ml"],2, ",", ""),
                                            "fertilizer_name" =>  $results["fertilizer"]["name"],
                                        ])?>
                                    <?php elseif($results["fertilizer"]["ml"] > 0 && $results["additive"]["magnesium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_and_magnesium_missing_with_all_without_calcium", [
                                            "magnesium_additive_ml" =>  number_format($results["additive"]["magnesium"]["ml"],2, ",", ""),
                                            "magnesium_additive_concentration" =>  $results["additive"]["magnesium"]["concentration"],
                                            "magnesium_additive_name" =>  __("additive.".$results["additive"]["magnesium"]["name"]),
                                            "fertilizer_ml" =>  number_format($results["fertilizer"]["ml"],2, ",", ""),
                                            "fertilizer_name" =>  $results["fertilizer"]["name"],
                                        ])?>
                                    <?php elseif($results["additive"]["magnesium"]["ml"] > 0 && $results["additive"]["calcium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_and_magnesium_missing_with_all_additives", [
                                            "magnesium_additive_ml" =>  number_format($results["additive"]["magnesium"]["ml"],2, ",", ""),
                                            "magnesium_additive_concentration" =>  $results["additive"]["magnesium"]["concentration"],
                                            "magnesium_additive_name" =>  __("additive.".$results["additive"]["magnesium"]["name"]),
                                            "calcium_additive_ml" =>  number_format($results["additive"]["calcium"]["ml"],2, ",", ""),
                                            "calcium_additive_concentration" =>  $results["additive"]["calcium"]["concentration"],
                                            "calcium_additive_name" =>  __("additive.".$results["additive"]["calcium"]["name"]),
                                        ])?>
                                    <?php elseif($results["additive"]["magnesium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_and_magnesium_missing_with_magnesium_additive", [
                                            "magnesium_additive_ml" =>  number_format($results["additive"]["magnesium"]["ml"],2, ",", ""),
                                            "magnesium_additive_concentration" =>  $results["additive"]["magnesium"]["concentration"],
                                            "magnesium_additive_name" =>  __("additive.".$results["additive"]["magnesium"]["name"]),
                                        ])?>
                                    <?php elseif($results["additive"]["calcium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_and_magnesium_missing_with_calcium_additive", [
                                            "calcium_additive_ml" =>  number_format($results["additive"]["calcium"]["ml"],2, ",", ""),
                                            "calcium_additive_concentration" =>  $results["additive"]["calcium"]["concentration"],
                                            "calcium_additive_name" =>  __("additive.".$results["additive"]["calcium"]["name"]),
                                        ])?>
                                    <?php elseif($results["fertilizer"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_and_magnesium_missing_without_additive", [
                                            "fertilizer_ml" =>  number_format($results["fertilizer"]["ml"],2, ",", ""),
                                            "fertilizer_name" =>  $results["fertilizer"]["name"],
                                        ])?>
                                    <?php endif; ?>
                                <?php elseif ($results["missing"]["calcium"] < 0 || $results["missing"]["magnesium"] < 0): ?>
                                    <?php if($results["fertilizer"]["ml"] > 0 && $results["additive"]["magnesium"]["ml"] > 0 && $results["additive"]["calcium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_high_with_all_additives", [
                                            "magnesium_additive_ml" =>  number_format($results["additive"]["magnesium"]["ml"],2, ",", ""),
                                            "magnesium_additive_concentration" =>  $results["additive"]["magnesium"]["concentration"],
                                            "magnesium_additive_name" =>  __("additive.".$results["additive"]["magnesium"]["name"]),
                                            "calcium_additive_ml" =>  number_format($results["additive"]["calcium"]["ml"],2, ",", ""),
                                            "calcium_additive_concentration" =>  $results["additive"]["calcium"]["concentration"],
                                            "calcium_additive_name" =>  __("additive.".$results["additive"]["calcium"]["name"]),
                                            "fertilizer_ml" =>  number_format($results["fertilizer"]["ml"],2, ",", ""),
                                            "fertilizer_name" =>  $results["fertilizer"]["name"],
                                        ])?>
                                    <?php elseif($results["fertilizer"]["ml"] > 0 && $results["additive"]["magnesium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_high_with_all_without_calcium", [
                                            "magnesium_additive_ml" =>  number_format($results["additive"]["magnesium"]["ml"],2, ",", ""),
                                            "magnesium_additive_concentration" =>  $results["additive"]["magnesium"]["concentration"],
                                            "magnesium_additive_name" =>  __("additive.".$results["additive"]["magnesium"]["name"]),
                                            "fertilizer_ml" =>  number_format($results["fertilizer"]["ml"],2, ",", ""),
                                            "fertilizer_name" =>  $results["fertilizer"]["name"],
                                        ])?>
                                    <?php elseif($results["fertilizer"]["ml"] > 0 && $results["additive"]["calcium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_high_with_all_without_magnesium", [
                                            "calcium_additive_ml" =>  number_format($results["additive"]["calcium"]["ml"],2, ",", ""),
                                            "calcium_additive_concentration" =>  $results["additive"]["calcium"]["concentration"],
                                            "calcium_additive_name" =>  __("additive.".$results["additive"]["calcium"]["name"]),
                                            "fertilizer_ml" =>  number_format($results["fertilizer"]["ml"],2, ",", ""),
                                            "fertilizer_name" =>  $results["fertilizer"]["name"],
                                        ])?>
                                    <?php elseif($results["additive"]["magnesium"]["ml"] > 0 && $results["additive"]["calcium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_high_with_additive", [
                                            "magnesium_additive_ml" =>  number_format($results["additive"]["magnesium"]["ml"],2, ",", ""),
                                            "magnesium_additive_concentration" =>  $results["additive"]["magnesium"]["concentration"],
                                            "magnesium_additive_name" =>  __("additive.".$results["additive"]["magnesium"]["name"]),
                                        ])?>
                                    <?php elseif($results["additive"]["magnesium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_high_with_magnesium_additive", [
                                            "magnesium_additive_ml" =>  number_format($results["additive"]["magnesium"]["ml"],2, ",", ""),
                                            "magnesium_additive_concentration" =>  $results["additive"]["magnesium"]["concentration"],
                                            "magnesium_additive_name" =>  __("additive.".$results["additive"]["magnesium"]["name"]),
                                        ])?>
                                    <?php elseif($results["additive"]["calcium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_high_with_calcium_additive", [
                                            "calcium_additive_ml" =>  number_format($results["additive"]["calcium"]["ml"],2, ",", ""),
                                            "calcium_additive_concentration" =>  $results["additive"]["calcium"]["concentration"],
                                            "calcium_additive_name" =>  __("additive.".$results["additive"]["calcium"]["name"]),
                                        ])?>
                                    <?php else: ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_high_without_additive", [
                                            "fertilizer_ml" =>  number_format($results["fertilizer"]["ml"],2, ",", ""),
                                            "fertilizer_name" =>  $results["fertilizer"]["name"],
                                        ])?>
                                    <?php endif; ?>
                                <?php elseif ($results["fertilizer"]["ml"] > 0 || $results["additive"]["magnesium"]["ml"] > 0 || $results["additive"]["calcium"]["ml"] > 0): ?>
                                    <?php if ($results["fertilizer"]["ml"] > 0 && $results["additive"]["magnesium"]["ml"] > 0 && $results["additive"]["calcium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_and_magnesium_ok_with_all_additives_and_fertilizer", [
                                            "magnesium_additive_ml" =>  number_format($results["additive"]["magnesium"]["ml"],2, ",", ""),
                                            "magnesium_additive_concentration" =>  $results["additive"]["magnesium"]["concentration"],
                                            "magnesium_additive_name" =>  __("additive.".$results["additive"]["magnesium"]["name"]),
                                            "calcium_additive_ml" =>  number_format($results["additive"]["calcium"]["ml"],2, ",", ""),
                                            "calcium_additive_concentration" =>  $results["additive"]["calcium"]["concentration"],
                                            "calcium_additive_name" =>  __("additive.".$results["additive"]["calcium"]["name"]),
                                            "fertilizer_ml" =>  number_format($results["fertilizer"]["ml"],2, ",", ""),
                                            "fertilizer_name" =>  $results["fertilizer"]["name"],
                                        ])?>
                                    <?php elseif ($results["fertilizer"]["ml"] > 0 && $results["additive"]["magnesium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_and_magnesium_ok_with_additive_and_fertilizer", [
                                            "magnesium_additive_ml" =>  number_format($results["additive"]["magnesium"]["ml"],2, ",", ""),
                                            "magnesium_additive_concentration" =>  $results["additive"]["magnesium"]["concentration"],
                                            "magnesium_additive_name" =>  __("additive.".$results["additive"]["magnesium"]["name"]),
                                            "fertilizer_ml" =>  number_format($results["fertilizer"]["ml"],2, ",", ""),
                                            "fertilizer_name" =>  $results["fertilizer"]["name"],
                                        ])?>
                                    <?php elseif ($results["fertilizer"]["ml"] > 0 && $results["additive"]["calcium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_and_magnesium_ok_with_calcium_additive_and_fertilizer", [
                                            "calcium_additive_ml" =>  number_format($results["additive"]["calcium"]["ml"],2, ",", ""),
                                            "calcium_additive_concentration" =>  $results["additive"]["calcium"]["concentration"],
                                            "calcium_additive_name" =>  __("additive.".$results["additive"]["calcium"]["name"]),
                                            "fertilizer_ml" =>  number_format($results["fertilizer"]["ml"],2, ",", ""),
                                            "fertilizer_name" =>  $results["fertilizer"]["name"],
                                        ])?>
                                    <?php elseif ($results["additive"]["magnesium"]["ml"] > 0): ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_and_magnesium_ok_with_magnesium_additive_without_fertilizer", [
                                            "magnesium_additive_ml" =>  number_format($results["additive"]["magnesium"]["ml"],2, ",", ""),
                                            "magnesium_additive_concentration" =>  $results["additive"]["magnesium"]["concentration"],
                                            "magnesium_additive_name" =>  __("additive.".$results["additive"]["magnesium"]["name"]),
                                        ])?>
                                    <?php else: ?>
                                        <?php echo __("content.calculator.result.deficiency.state.calcium_and_magnesium_ok_with_fertilizer_without_additive", [
                                            "fertilizer_ml" =>  number_format($results["fertilizer"]["ml"],2, ",", ""),
                                            "fertilizer_name" =>  $results["fertilizer"]["name"],
                                        ])?>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php echo __("content.calculator.result.deficiency.state.no_action_needed")?>
                                <?php endif; ?>
                                <br />

                                <?php echo __("content.calculator.result.deficiency.state.suggested_amount", [
                                    "calcium" =>  number_format($results["target"]["elements"]["calcium"],2, ",", ""),
                                    "magnesium" =>  number_format($results["target"]["elements"]["magnesium"],2, ",", ""),
                                ])?>


                            </div>
                            <div class="w-full  px-3 py-1 text-left">

                        </div>
                        </div>

                    </div>
                <?php endforeach; ?>
                <?php endif; ?>

            <?php endif; ?>
        </div>
    </div>
</div>

<script type="application/javascript">
    (function(){
        // Clear the URL when the form has changed
        document.querySelectorAll("form select, form input").forEach(function(element){
            element.addEventListener("change", function(){
                window.history.pushState({}, "", "/");
            });
        });
    })();
</script>