            <div class="w-full opacity-50 py-8">
                <div class="w-full text-center">
                    Copyright &copy; <?php echo \Carbon\Carbon::now()->year ?> by Webklex
                    <br />
                    <a href="https://www.webklex.com/impressum" class="text-red-500"><?php echo __("footer.impress") ?></a>
                </div>
            </div>
        </div>
    </body>
</html>