<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CalMag <?php echo __("header.logo.appendix")?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/css/app.css" rel="stylesheet">
    <link href="/css/tailwind.css" rel="stylesheet">
</head>
<body class="bg-slate-900 text-slate-200 flex flex-wrap justify-center">
    <div id="main" class="w-full flex flex-wrap justify-center">

        <div class="w-full border-b border-slate-700 bg-slate-800 px-4 md:px-6 py-2 shadow-lg justify-center justify-items-center align-middle">
            <div class="container px-2">
                <div class="flex align-middle justify-end justify-items-end">
                    <div class="flex-none text-slate-300 font-semibold text-3xl pb-1 align-middle">
                        <span class="text-red-500 font-light">Cal</span>
                        <span class="text-sky-100 font-light -ml-1">Mag</span>
                        <span class="pl-1"><?php echo __("header.logo.appendix")?></span>
                        <span class="text-xs">v<?php echo Webklex\CalMag\Application::VERSION; ?></span>
                    </div>
                    <div class="pl-4 grow text-slate-300 font-light grid gap-1 justify-items-end content-center">
                        <a href="https://github.com/webklex/calmag" class="border-1 border-red-500 text-red-200 px-2">
                            Fork me
                        </a>
                    </div>
                </div>
            </div>
        </div>
