<!DOCTYPE html>
<html lang="<?php echo __('region.default')?>">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CalMag <?php echo __("header.logo.appendix")?></title>
    <meta name="title" content="<?php echo __("header.og.title")?>">
    <meta name="description" content="<?php echo __("header.og.description")?>">
    <meta name="author" content="Webklex">

    <?php $link = (empty($_SERVER['HTTPS']) ? 'http' : 'https') . "://$_SERVER[HTTP_HOST]/"; ?>
    <meta property="og:title" content="<?php echo __("header.og.title")?>">
    <meta property="og:description" content="<?php echo __("header.og.description")?>">
    <meta property="og:url" content="<?php echo $link ?>">
    <meta property="og:image" content="<?php echo $link ?>images/og_image_small.png">
    <meta property="og:type" content="website">
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/css/app.css" rel="stylesheet">
    <link href="/css/tailwind.css" rel="stylesheet">
</head>
<body class="bg-slate-900 text-slate-200 flex flex-wrap justify-center">
    <div id="main" class="w-full flex flex-wrap justify-center">

        <div class="w-full border-b border-slate-700 bg-slate-800 px-4 md:px-6 py-2 shadow-lg justify-center justify-items-center align-middle">
            <div class="container px-2">
                <div class="flex align-middle justify-end justify-items-end">
                    <div class="flex-none text-slate-300 font-semibold text-3xl pb-1 align-middle">
                        <span class="text-red-500 font-light">Cal</span>
                        <span class="text-sky-100 font-light -ml-1">Mag</span>
                        <span class="pl-1"><?php echo __("header.logo.appendix")?></span>
                        <span class="text-xs">v<?php echo Webklex\CalMag\Application::VERSION; ?></span>
                    </div>
                    <div class="pl-4 grow text-slate-300 font-light grid gap-1 justify-items-end content-center ">
                        <div class="flex flex-wrap justify-items-end">
                            <a href="https://discord.gg/xy9waNZju2" class="px-2 inline-block" title="Pott Planter Discord">
                                <img src="/images/pott_planter_discord.png" class="h-8" alt="Pott Planter Discord">
                            </a>
                            <a href="https://github.com/webklex/calmag" class="text-red-700 px-2 w-6 pt-1 inline-block" title="Fork me on GitHub">
                                <i class="fa-brands fa-github-alt fa-2xl"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
